apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-ping-app
  template:
    metadata:
      labels:
        app: flask-ping-app
    spec:
      containers:
      - name: flask-ping-app
        image: puneetk438/flask-ping-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-ping-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-ping-app
